# Generated by Django 5.2.7 on 2025-10-30 20:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profile Picture')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, verbose_name='Home Address')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='Lebanon', max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Student ID')),
                ('class_level', models.CharField(choices=[('kindergarten1', 'Kindergarten 1'), ('kindergarten2', 'Kindergarten 2'), ('kindergarten3', 'Kindergarten 3'), ('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3'), ('grade_4', 'Grade 4'), ('grade_5', 'Grade 5'), ('grade_6', 'Grade 6'), ('grade_7', 'Grade 7'), ('grade_8', 'Grade 8'), ('grade_9', 'Grade 9')], max_length=20, verbose_name='Class Level')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Enrollment Date')),
                ('expected_graduation_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Expected Graduation Year')),
                ('parent_name', models.CharField(max_length=100, verbose_name='Parent/Guardian Name')),
                ('parent_email', models.EmailField(max_length=254, verbose_name='Parent/Guardian Email')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='Parent/Guardian Phone')),
                ('parent_occupation', models.CharField(blank=True, max_length=100, verbose_name='Parent Occupation')),
                ('medical_conditions', models.TextField(blank=True, verbose_name='Medical Conditions')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('medication', models.TextField(blank=True, verbose_name='Current Medications')),
                ('emergency_contact_name', models.CharField(max_length=100, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name='Emergency Contact Phone')),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Attendance Rate %')),
                ('current_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Current GPA')),
                ('major_subject', models.CharField(blank=True, max_length=100, verbose_name='Major Subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['class_level', 'student_id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profile Picture')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, verbose_name='Home Address')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='Lebanon', max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Employee ID')),
                ('employee_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('substitute', 'Substitute Teacher')], max_length=20, verbose_name='Employment Type')),
                ('department', models.CharField(choices=[('dep_a', 'Main Department'), ('dep_b', 'New Department'), ('dep_both', 'Both Departments')], max_length=50, verbose_name='Department')),
                ('position', models.CharField(default='Teacher', max_length=100, verbose_name='Job Position')),
                ('qualifications', models.TextField(blank=True, verbose_name='Qualifications')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Area of Specialization')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='Hire Date')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salary')),
                ('subjects_taught', models.CharField(blank=True, max_length=500, verbose_name='Subjects Taught')),
                ('is_homeroom_teacher', models.BooleanField(default=False, verbose_name='Homeroom Teacher')),
                ('max_classes', models.PositiveIntegerField(default=5, verbose_name='Maximum Classes')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Emergency Contact Phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
                'ordering': ['department', 'employee_id'],
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_type', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Type',
                'verbose_name_plural': 'User Types',
                'ordering': ['user_type'],
            },
        ),
    ]
