# Generated by Django 5.2.7 on 2025-11-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_studentprofile_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='current_gpa',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='major_subject',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='emergency_contact_name',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Parent/Guardian Email'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parent/Guardian Name'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='parent_occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parent Occupation'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Parent/Guardian Phone'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Contact Phone'),
        ),
    ]
