# Generated by Django 5.2.7 on 2026-01-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_studentprofile_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='absences',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total Absences'),
        ),
    ]
