# Generated by Django 5.2.7 on 2026-01-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_studentprofile_absences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='absences',
            new_name='absence_value',
        ),
    ]
