# Generated by Django 5.2.7 on 2026-01-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_absences_studentprofile_absence_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='carnet_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Carnet 1 Grade'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='carnet_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Carnet 2 Grade'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='carnet_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Carnet 3 Grade'),
        ),
    ]
