# Generated by Django 5.2.7 on 2026-01-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('history', 'History'), ('geography', 'Geography'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('french', 'French'), ('arabic', 'Arabic'), ('art', 'Art'), ('music', 'Music'), ('pe', 'Physical Education'), ('computer', 'Computer Science')], max_length=50)),
                ('class_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='classes.class')),
            ],
            options={
                'verbose_name': 'Class Announcement',
                'verbose_name_plural': 'Class Announcements',
            },
        ),
    ]
