# Generated by Django 5.2.7 on 2026-01-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnews',
            name='tag',
            field=models.CharField(blank=True, default='General', max_length=50, null=True),
        ),
    ]
