# Generated by Django 5.2.7 on 2026-01-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_latestnews_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('announcment_for', models.CharField(blank=True, choices=[('All', 'All Users'), ('Students', 'Students Only'), ('Teachers', 'Teachers Only')], default='All', max_length=50, null=True)),
            ],
        ),
    ]
